<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8"/>
        <title>Slim 3</title>
        <link href='//fonts.googleapis.com/css?family=Lato:300' rel='stylesheet' type='text/css'>
        <style>
        </style>
    </head>
    <body>
        <h1>Slim</h1>
        <div>a microframework for PHP</div>

            <h2>Hello <?= htmlspecialchars($cowNoise); ?>!</h2>
            <h2>Hello <?= htmlspecialchars($name); ?>!</h2>
            <h2>Hello <?= htmlspecialchars($chickenNoise)?></h2>
            <p>Try <a href="http://www.slimframework.com">SlimFramework</a></p>
    </body>
</html>